const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const SECTIONS=['inicio','conceptos','simulador','comprobacion','recursos','cierre'];
let conceptIndex=0,resourceContext=null,currentUtter=null,toneCtx=null;
const state={section:'inicio',font:1,sound:true,layout:'auto',theme:'light',concepts:{},quizOrder:[],quizIndex:0,quizStates:{},quizScore:0,lab:null,opening:{selected:null},closingQ:null};

function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function randomInt(max){if(max<=1)return 0;try{if(window.crypto?.getRandomValues){const limit=Math.floor(0x100000000/max)*max,buf=new Uint32Array(1);let x;do{window.crypto.getRandomValues(buf);x=buf[0];}while(x>=limit);return x%max;}}catch(e){}return Math.floor(Math.random()*max);}
function shuffleIndices(len){const a=[...Array(len).keys()];for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function balancedPositions(items){const total=items.length;if(!total)return[];const optCount=Math.min(...items.map(x=>x.options.length));for(let attempt=0;attempt<1500;attempt++){const p=Array.from({length:total},()=>randomInt(optCount)),counts=Array(optCount).fill(0);p.forEach(x=>counts[x]++);const max=Math.max(...counts),unique=counts.filter(Boolean).length,maxAllowed=Math.max(1,Math.ceil(total/3));if(max<=maxAllowed&&unique>=Math.min(3,total,optCount))return p;}return shuffleIndices(total).map((_,i)=>i%optCount);}
let conceptCorrectPositions=balancedPositions(DATA.concepts),quizCorrectPositions=balancedPositions(DATA.quiz);
function orderWithTarget(q,target){const correct=q.options.findIndex(x=>x[1]);const others=shuffleIndices(q.options.length).filter(i=>i!==correct);others.splice(Math.min(target,others.length),0,correct);return others;}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),2300);}
function beep(kind='ok'){if(!state.sound)return;try{toneCtx=toneCtx||new (window.AudioContext||window.webkitAudioContext)();const o=toneCtx.createOscillator(),g=toneCtx.createGain();o.frequency.value=kind==='bad'?220:kind==='soft'?430:650;g.gain.setValueAtTime(.0001,toneCtx.currentTime);g.gain.exponentialRampToValueAtTime(.05,toneCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,toneCtx.currentTime+.10);o.connect(g);g.connect(toneCtx.destination);o.start();o.stop(toneCtx.currentTime+.11);}catch(e){}}

function go(section){if(!SECTIONS.includes(section))return;closeAllDialogs();state.section=section;$$('.section').forEach(s=>s.classList.toggle('active',s.id===section));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.go===section));window.scrollTo({top:0,behavior:'smooth'});if(section==='conceptos')renderConceptCards();if(section==='simulador')renderLab();if(section==='comprobacion')ensureQuiz();if(section==='recursos')renderResources();if(section==='cierre')renderClosingReview();}
function openDialog(id){const d=$('#'+id);if(!d)return;try{if(!d.open)d.showModal();document.body.classList.add('dialog-open');}catch(e){d.setAttribute('open','');document.body.classList.add('dialog-open');}}
function closeDialog(id){const d=$('#'+id);if(!d)return;stopSpeech();$$('audio,video',d).forEach(m=>{try{m.pause();}catch(e){}});try{if(d.open)d.close();}catch(e){d.removeAttribute('open');}if(!$$('dialog[open]').length)document.body.classList.remove('dialog-open');}
function closeAllDialogs(){$$('dialog[open]').forEach(d=>closeDialog(d.id));}
function toggleFullscreen(el){if(!document.fullscreenElement){el.requestFullscreen?.().catch(()=>{});}else document.exitFullscreen?.().catch(()=>{});}
function applyLayout(){let active=state.layout;if(active==='auto')active=innerWidth/Math.max(innerHeight,1)>1.5?'16x9':'4x3';document.documentElement.dataset.layoutActive=active;document.documentElement.dataset.layoutMode=state.layout;$('#layoutSelect').value=state.layout;}
function updateFont(){document.documentElement.style.setProperty('--font-scale',state.font.toFixed(2));}
function applyTheme(){document.documentElement.dataset.theme=state.theme;const b=$('#themeBtn');b.textContent=state.theme==='dark'?'☀':'◐';b.setAttribute('aria-pressed',state.theme==='dark'?'true':'false');}

/* speech */
function pickVoice(){const vs=speechSynthesis.getVoices?.()||[];for(const lang of ['es-PE','es-419','es-MX','es-US','es']){const v=vs.find(x=>(x.lang||'').toLowerCase()===lang.toLowerCase())||vs.find(x=>(x.lang||'').toLowerCase().startsWith(lang.toLowerCase()));if(v)return v;}return vs.find(x=>(x.lang||'').toLowerCase().startsWith('es'))||null;}
function speak(text){if(!text||!('speechSynthesis'in window))return;stopSpeech();currentUtter=new SpeechSynthesisUtterance(text);currentUtter.lang='es-PE';const v=pickVoice();if(v)currentUtter.voice=v;currentUtter.rate=.96;speechSynthesis.speak(currentUtter);}
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();currentUtter=null;} function pauseSpeech(){speechSynthesis?.pause?.();} function resumeSpeech(){speechSynthesis?.resume?.();}
function speechControlsHTML(){return `<div class="speech-controls"><button type="button" data-speech="read">▶ Leer</button><button type="button" data-speech="explain">💡 Explicar</button><button type="button" data-speech="pause">Ⅱ Pausar</button><button type="button" data-speech="resume">↻ Continuar</button><button type="button" data-speech="stop">■ Detener</button></div>`;}
function bindSpeechControls(root,getText){$$('[data-speech]',root).forEach(b=>b.onclick=()=>{const a=b.dataset.speech;if(a==='pause')return pauseSpeech();if(a==='resume')return resumeSpeech();if(a==='stop')return stopSpeech();const t=getText(a);if(t)speak(t);});}
function slideText(slide,type){return RT.ppt?.[Math.max(0,slide-1)]?.[type]||'';}

/* opening detonante */
const OPENING_OPTIONS=[
  'Sí. Si está registrado correctamente, basta para considerar que la operación fue bien controlada.',
  'No. El registro es una evidencia, pero también deben verificarse autorización, ejecución de controles y contexto de riesgo.',
  'Solo depende del monto; las operaciones pequeñas no necesitan revisar autorización ni evidencia.'
];
function renderOpening(){const host=$('#openingQuestion');if(!host)return;host.innerHTML=`<div class="opening-answer-options">${OPENING_OPTIONS.map((t,i)=>`<button class="opening-answer ${state.opening.selected===i?'selected':''}" data-open-opt="${i}"><strong>${String.fromCharCode(65+i)}.</strong> ${esc(t)}</button>`).join('')}</div><div class="opening-answer-status">${state.opening.selected===null?'Selecciona una respuesta para registrarla. No se calificará ahora.':'✓ Respuesta inicial registrada. Se conservará hasta el cierre.'}</div>`;$$('[data-open-opt]',host).forEach(b=>b.onclick=()=>{state.opening.selected=Number(b.dataset.openOpt);beep('soft');renderOpening();});}

/* question engine */
function createQState(q,order=null){return{order:order||shuffleIndices(q.options.length),selected:null,firstWrong:null,phase:'select1'};}
function questionDone(s){return s&&['correct','route'].includes(s.phase);}
function feedbackGrid(items){return `<div class="feedback-grid">${items.map(x=>`<div><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p></div>`).join('')}</div>`;}
function renderQuestion(host,q,s,cfg={}){
  const locked=s.phase==='firstWrong'||questionDone(s);
  const opts=s.order.map((orig,pos)=>{const [text,ok]=q.options[orig],selected=s.selected===orig,firstWrong=s.firstWrong===orig,route=s.phase==='route';return `<button type="button" class="${['option',selected?'selected':'',firstWrong?'wrong-choice':'',route&&ok?'correct-choice':''].filter(Boolean).join(' ')}" data-opt="${orig}" ${(locked||(s.phase==='select2'&&firstWrong))?'disabled':''}><strong>${String.fromCharCode(65+pos)}.</strong> ${esc(text)}</button>`;}).join('');
  let feedback='';
  if(s.phase==='correct')feedback=`<div class="feedback good" data-feedback><div class="feedback-title"><span>✓</span><div><h4>Respuesta correcta</h4><p>Revisa el razonamiento, no solo la alternativa.</p></div></div><p class="feedback-main">${esc(q.correct)}</p>${feedbackGrid([['Por qué es correcta',q.correct],['Cómo se aplica',q.application],['Por qué no las otras',q.contrast],['Regla transferible',q.rule]])}</div>`;
  else if(s.phase==='firstWrong'){const chosen=q.options[s.firstWrong]?.[0]||'';feedback=`<div class="feedback bad" data-feedback><div class="feedback-title"><span>↺</span><div><h4>Primer intento incorrecto</h4><p>Todavía no mostramos la respuesta correcta.</p></div></div><p class="feedback-main">${esc(q.wrong1)}</p>${feedbackGrid([['Tu elección',chosen],['Qué revisar','Busca evidencia, propósito del control y coherencia con el proceso antes de volver a elegir.'],['Pista',q.rule],['Segundo intento','Pulsa “Cambiar respuesta · segundo intento”. La alternativa anterior quedará bloqueada.']])}</div>`;}
  else if(s.phase==='route'){const correct=q.options.find(x=>x[1])?.[0]||'';feedback=`<div class="feedback route" data-feedback><div class="feedback-title"><span>→</span><div><h4>Ruta correcta</h4><p>El segundo intento también fue incorrecto. Reconstruimos el criterio.</p></div></div><p class="feedback-main">${esc(q.routeSummary)}</p><ol class="route-steps">${(q.route||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol>${feedbackGrid([['Alternativa defendible',correct],['Por qué corresponde',q.correct],['Aplicación',q.application],['Por qué se descartan las otras',q.contrast],['Regla que debes conservar',q.rule]])}</div>`;}
  const label=s.phase==='select1'?'Intento 1 de 2':s.phase==='firstWrong'?'Primer intento revisado':s.phase==='select2'?'Intento 2 de 2':s.phase==='correct'?'Pregunta completada':'Ruta correcta';
  const actions=s.phase==='select1'||s.phase==='select2'?`<button class="btn primary" data-check ${s.selected===null?'disabled':''}>Comprobar respuesta</button>`:s.phase==='firstWrong'?`<button class="btn orange" data-change>Cambiar respuesta · segundo intento</button>`:'';
  host.innerHTML=`<div class="qbox"><div class="qmeta"><span class="attempt-badge">${label}</span></div><div class="question-prompt"><span class="question-label">PREGUNTA</span><p>${esc(q.text||q.question||'')}</p></div><div class="options">${opts}</div><div class="qactions">${actions}</div>${feedback}</div>`;
  $$('[data-opt]',host).forEach(b=>b.onclick=()=>{if(locked)return;s.selected=Number(b.dataset.opt);beep('soft');renderQuestion(host,q,s,cfg);});
  $('[data-check]',host)?.addEventListener('click',()=>{if(s.selected===null)return;const ok=!!q.options[s.selected][1];if(ok){s.phase='correct';beep('ok');renderQuestion(host,q,s,cfg);cfg.onFinish?.({correct:true});setTimeout(()=>$('[data-feedback]',host)?.scrollIntoView({behavior:'smooth',block:'nearest'}),50);}else if(s.phase==='select1'){s.firstWrong=s.selected;s.phase='firstWrong';beep('bad');renderQuestion(host,q,s,cfg);setTimeout(()=>$('[data-feedback]',host)?.scrollIntoView({behavior:'smooth',block:'nearest'}),50);}else{s.phase='route';beep('bad');renderQuestion(host,q,s,cfg);cfg.onFinish?.({correct:false,route:true});setTimeout(()=>$('[data-feedback]',host)?.scrollIntoView({behavior:'smooth',block:'nearest'}),50);}});
  $('[data-change]',host)?.addEventListener('click',()=>{s.phase='select2';s.selected=null;renderQuestion(host,q,s,cfg);});
}

/* concepts */
function conceptState(c){if(!state.concepts[c.id]){const idx=DATA.concepts.indexOf(c);state.concepts[c.id]={openQ:false,q:createQState(c,orderWithTarget(c,conceptCorrectPositions[idx]??randomInt(c.options.length)))};}return state.concepts[c.id];}
function conceptDone(c){return questionDone(conceptState(c).q);}
function renderConceptCards(){const host=$('#conceptGrid');host.innerHTML=DATA.concepts.map((c,i)=>`<button class="concept-card" data-concept="${i}">${conceptDone(c)?'<span class="concept-status">✓ Revisada</span>':''}<div class="concept-card-inner"><div class="concept-face concept-front"><div class="concept-slide-thumb"><img src="assets/ppt/slide-${String(c.slide).padStart(2,'0')}.png" alt="${esc(c.title)}"></div><div class="concept-front-copy"><span class="concept-number">${c.number}</span><h3>${esc(c.title)}</h3><p>${esc(c.summary)}</p><small>Abre para revisar concepto y pregunta.</small></div></div><div class="concept-face concept-back"><span class="concept-number">${c.number}</span><h3>${esc(c.title)}</h3><p>${esc(c.meaning)}</p><span class="open-cue">Toca / haz clic para abrir →</span></div></div></button>`).join('');$$('[data-concept]',host).forEach(b=>b.onclick=()=>{conceptIndex=Number(b.dataset.concept);renderConceptModal();openDialog('conceptModal');});const done=DATA.concepts.filter(conceptDone).length;$('#conceptProgress').textContent=`${done} / ${DATA.concepts.length} revisadas`;}
function conceptExtra(c){
  if(c.id==='auditoria')return `<div class="actions"><button class="btn secondary" data-open-resource="ppt" data-resource-index="3">Comparar auditoría interna vs. externa</button></div>`;
  if(c.id==='tecnicas')return `<div class="actions"><button class="btn secondary" data-open-resource="ppt" data-resource-index="5">Ver pruebas sustantivas y de cumplimiento</button></div>`;
  if(c.id==='control')return `<div class="actions"><button class="btn orange" data-open-resource="video-agencias">▶ Ver video corto · Blindaje de una transacción</button><button class="btn secondary" data-open-resource="ppt" data-resource-index="9">Ver aplicación en la agencia</button></div>`;
  if(c.id==='laft')return `<div class="actions"><button class="btn secondary" data-open-resource="ppt" data-resource-index="15">Ver ecosistema de prevención</button><button class="btn secondary" data-open-resource="infographic">Ver infografía integradora</button></div>`;
  return '';
}
function renderConceptModal(){const c=DATA.concepts[conceptIndex],s=conceptState(c),slide=`assets/ppt/slide-${String(c.slide).padStart(2,'0')}.png`;$('#conceptKicker').textContent=`Tarjeta ${c.number} · concepto aplicado`;$('#conceptTitle').textContent=c.title;$('#conceptCounter').textContent=`${conceptIndex+1} / ${DATA.concepts.length}`;$('#prevConcept').disabled=conceptIndex===0;$('#nextConcept').disabled=conceptIndex===DATA.concepts.length-1;const qp=s.openQ?'<div id="conceptQuestion"></div>':`<div class="question-gate"><div><strong>¿Listo para comprobar?</strong><span>Revisa primero el concepto y los apoyos.</span></div><button class="btn primary" data-show-question>Ver pregunta →</button></div>`;$('#conceptBody').innerHTML=`<div class="concept-modal-layout"><div class="concept-image-column"><img class="concept-main-slide" src="${slide}" alt="Diapositiva de ${esc(c.title)}" data-image="${slide}">${speechControlsHTML()}</div><div class="concept-detail-scroll"><section class="detail-box"><span class="mini-label">QUÉ SIGNIFICA</span><p>${esc(c.meaning)}</p></section><section class="detail-box example"><span class="mini-label">EJEMPLO</span><p>${esc(c.example)}</p></section><section class="detail-box warning"><span class="mini-label">ERROR QUE CONVIENE EVITAR</span><p>${esc(c.error)}</p></section>${c.audio?`<div class="audio-pista"><strong>🎧 Cápsula de audio antes de responder</strong><p>Extracto breve del audio completo de la sesión.</p><audio controls preload="metadata"><source src="${c.audio}" type="audio/mp4"></audio></div>`:''}${conceptExtra(c)}${qp}</div></div>`;bindSpeechControls($('#conceptBody'),type=>slideText(c.slide,type));$('[data-image]',$('#conceptBody'))?.addEventListener('click',e=>openImage(e.currentTarget.dataset.image,e.currentTarget.alt));$$('[data-open-resource]',$('#conceptBody')).forEach(b=>b.onclick=()=>openResource(b.dataset.openResource,Number(b.dataset.resourceIndex||0)));$('[data-show-question]',$('#conceptBody'))?.addEventListener('click',()=>{s.openQ=true;renderConceptModal();setTimeout(()=>$('#conceptQuestion')?.scrollIntoView({behavior:'smooth',block:'start'}),30);});if(s.openQ)renderQuestion($('#conceptQuestion'),c,s.q,{onFinish:renderConceptCards});}

/* LAB */
const AUDIT_Q={
  text:'La conciliación bancaria cuadra, pero no existe evidencia de revisión independiente. ¿Qué combinación de trabajo de auditoría es más adecuada?',
  options:[
    ['Inspeccionar la conciliación y su evidencia de aprobación, y aplicar una prueba de cumplimiento para verificar segregación y revisión.',1],
    ['Limitarse a recalcular el saldo y concluir que todo control funcionó porque el resultado matemático coincide.',0],
    ['Entrevistar únicamente al cajero y omitir documentos, porque la investigación verbal sustituye cualquier otra técnica.',0],
    ['Solicitar una auditoría externa completa antes de revisar el procedimiento interno que originó la observación.',0]
  ],
  correct:'La cifra ya coincide; el punto crítico es demostrar si el control de revisión y segregación se ejecutó. La inspección de evidencia y la prueba de cumplimiento responden esa pregunta.',
  application:'La auditoría debe adaptar técnica y prueba al objetivo específico.',contrast:'Los distractores confunden exactitud numérica con cumplimiento o sustituyen evidencia documental por una única fuente.',rule:'Elige técnica según la evidencia que necesitas obtener.',wrong1:'El problema principal no es cuánto suma la conciliación, sino si la revisión independiente ocurrió y puede demostrarse.',route:['Identifica el control esperado.','Busca evidencia de revisión.','Comprueba segregación.','Concluye sobre la eficacia del control.'],routeSummary:'La Ruta correcta se concentra en el procedimiento y su evidencia.'
};
const CONTROL_SCENARIOS={
  arqueo:{title:'Saldo correcto · arqueo desactualizado',summary:'El saldo de caja coincide con el sistema, pero el último arqueo sorpresivo fue realizado hace dos meses.',audio:'assets/pista_04.m4a',q:{text:'¿Qué cambia con esta información adicional?',options:[['El saldo correcto no demuestra que el control periódico se ejecute con la frecuencia prevista; corresponde observar y regularizar el control.',1],['Nada cambia: si el saldo coincide, la antigüedad del arqueo deja de ser relevante para la evaluación del control.',0],['Debe asumirse automáticamente un faltante de efectivo aunque no exista ninguna diferencia entre caja y sistema.',0],['El arqueo solo importa en auditoría externa y no forma parte de la primera línea de defensa de una agencia.',0]],correct:'El dato cuantitativo es favorable, pero la evidencia de control es insuficiente para demostrar ejecución oportuna.',application:'Distingue resultado de la operación y funcionamiento del control.',contrast:'Los distractores ignoran frecuencia o inventan un faltante no observado.',rule:'Resultado correcto ≠ control oportunamente ejecutado.',wrong1:'Pregunta qué evidencia demuestra que el control se ejecuta con la frecuencia prevista.',route:['Confirma saldo.','Revisa fecha del control.','Compara con frecuencia prevista.','Emite observación sin inventar diferencias.'],routeSummary:'La Ruta correcta separa saldo y eficacia del control.'}},
  segregacion:{title:'Conciliación correcta · misma persona prepara y revisa',summary:'La conciliación es matemáticamente correcta, pero el mismo colaborador la preparó y aprobó.',audio:'assets/pista_04.m4a',q:{text:'¿Cuál es la principal preocupación?',options:[['Existe debilidad de segregación: una sola persona concentra preparación y revisión, reduciendo la capacidad de detectar u ocultar errores.',1],['No existe preocupación porque la exactitud matemática elimina cualquier riesgo de concentración de funciones.',0],['El problema es exclusivamente contable y solo se corrige cambiando el monto final de la conciliación.',0],['La situación es aceptable siempre que el colaborador tenga antigüedad, aunque no exista revisión independiente.',0]],correct:'La observación es de diseño/ejecución del control: concentración de funciones incompatibles.',application:'La cifra no compensa la ausencia de revisión independiente.',contrast:'Los distractores convierten experiencia o exactitud en sustitutos de segregación.',rule:'Segregación protege incluso cuando el resultado actual parece correcto.',wrong1:'Piensa qué riesgo aparece cuando quien prepara también se aprueba a sí mismo.',route:['Identifica funciones.','Detecta concentración.','Define revisión independiente.','Deja evidencia.'],routeSummary:'La Ruta correcta fortalece segregación y trazabilidad.'}},
  inversiones:{title:'Inversión registrada · custodia y valuación sin evidencia',summary:'La adquisición está autorizada y registrada, pero no se encuentra evidencia reciente de custodia segregada ni de revisión de valuación.',audio:'assets/pista_04.m4a',q:{text:'¿Qué conclusión es más adecuada?',options:[['La operación requiere observación: aprobación y registro no sustituyen controles de custodia, valuación y seguimiento del activo.',1],['La autorización inicial basta para demostrar que todos los controles posteriores de inversión funcionan correctamente.',0],['La falta de evidencia de custodia solo afecta la rentabilidad, pero no la protección patrimonial ni la auditoría.',0],['Debe eliminarse la inversión del balance aunque todavía no se haya verificado si existe una pérdida o irregularidad real.',0]],correct:'El ciclo de control de inversiones incluye varias capas; una no reemplaza a las demás.',application:'Revisa autorización, registro, custodia, valuación y rendimientos.',contrast:'Los distractores sobrevaloran una capa o inventan una pérdida.',rule:'Control integral de inversiones = varias evidencias complementarias.',wrong1:'Revisa qué controles ocurren después de autorizar y registrar.',route:['Confirma aprobación.','Revisa registro.','Verifica custodia.','Comprueba valuación y seguimiento.'],routeSummary:'La Ruta correcta evalúa todo el ciclo de control.'}}
};
const LAFT_Q={
  text:'El cliente presenta un patrón inusual respecto de su perfil y la justificación económica inicial es incompleta. ¿Qué decisión preventiva es más adecuada?',
  options:[
    ['Completar la revisión de perfil y soportes, preservar trazabilidad y escalar al oficial de cumplimiento cuando la alerta lo amerite, sin presumir culpabilidad.',1],
    ['Procesar sin revisión porque todos los movimientos están registrados en el sistema y por ello deben considerarse legítimos.',0],
    ['Acusar al cliente y comunicarle los criterios internos exactos que activaron la alerta antes de reunir información adicional.',0],
    ['Rechazar automáticamente cualquier operación inusual sin aplicar el procedimiento interno de análisis ni considerar el perfil del cliente.',0]
  ],
  correct:'La prevención combina conocimiento del cliente, trazabilidad, análisis de la desviación y escalamiento especializado. La señal no sustituye la evaluación.',
  application:'El oficial de cumplimiento analiza alertas dentro del marco y política de la entidad.',contrast:'Los distractores ignoran la alerta, presumen culpabilidad o revelan criterios internos.',rule:'Inusual → analizar y documentar → escalar según política.',wrong1:'No confundas una señal de alerta con una conclusión automática.',route:['Compara con el perfil.','Reúne y valida soportes.','Conserva trazabilidad.','Escala a la función especializada si corresponde.'],routeSummary:'La Ruta correcta es preventiva, documentada y proporcional.'
};
function freshLab(){return{op:{auth:'',seg:'',support:'',trace:'',evaluated:false,outcome:''},audit:{q:createQState(AUDIT_Q)},control:{scenario:null,states:{},completed:false},laft:{checks:[false,false,false,false],reviewed:false,q:createQState(LAFT_Q)},reportOpen:false,missions:{op:false,audit:false,control:false,laft:false}};}
function ensureLab(){if(!state.lab)state.lab=freshLab();return state.lab;}
function missionStrip(){const l=ensureLab(),items=[['op','Operación y evidencia'],['audit','Trabajo de auditoría'],['control','¿Qué cambia si...?'],['laft','Prevención LA/FT']];return `<div class="mission-strip">${items.map((x,i)=>`<div class="mission-pill ${l.missions[x[0]]?'done':''}"><span>${i+1}</span><div><strong>${x[1]}</strong><small>${l.missions[x[0]]?'Completada':'Pendiente'}</small></div></div>`).join('')}</div>`;}
function updateMissions(){const l=ensureLab();l.missions.op=l.op.evaluated;l.missions.audit=questionDone(l.audit.q);l.missions.control=l.control.completed;l.missions.laft=l.laft.reviewed&&questionDone(l.laft.q);const done=Object.values(l.missions).filter(Boolean).length;$('#labBadge').textContent=`${done} / 4 misiones`;}
function operationOutcome(l){const vals=[l.op.auth,l.op.seg,l.op.support,l.op.trace];if(vals.some(x=>x===''))return null;const missing=[];if(l.op.auth==='No')missing.push('autorización');if(l.op.seg==='No')missing.push('segregación');if(l.op.support==='No')missing.push('sustento');if(l.op.trace==='No')missing.push('trazabilidad');return missing.length?`Operación observada. Falta validar: ${missing.join(', ')}. Puede analizarse, pero no debe tratarse como una operación plenamente controlada hasta resolver estas brechas.`:'Control base consistente: existen autorización, segregación, sustento y trazabilidad. Esto permite continuar, pero no elimina revisiones posteriores ni análisis de prevención.';}
function mission1(){const l=ensureLab();const fields=[['auth','Autorización dentro de facultades'],['seg','Segregación: registra ≠ autoriza'],['support','Documento / sustento de la operación'],['trace','Trazabilidad: usuario, hora y evidencia']];return `<section class="mission-section"><div class="mission-title"><div><span class="eyebrow dark">MISIÓN 1</span><h3>Revisa la operación antes de darla por segura</h3><p>Parte del contexto y construye tu conclusión a partir de la evidencia. El caso no te anticipa si los controles fueron suficientes.</p></div><span class="mission-tag">${l.missions.op?'✓ Completada':'Operación + evidencia'}</span></div><div class="case-summary-grid"><div><span>Cliente</span><strong>Comercial Andina S.A.C.</strong></div><div><span>Operación</span><strong>Transferencia S/ 48,500</strong></div><div><span>Relación</span><strong>3 años como cliente</strong></div><div><span>Contexto</span><strong>Beneficiario nuevo</strong></div></div><div class="evidence-grid">${fields.map(([k,label])=>`<label><span>${label}</span><select data-op="${k}"><option value="">— Verificar —</option><option value="Sí" ${l.op[k]==='Sí'?'selected':''}>Sí · verificado</option><option value="No" ${l.op[k]==='No'?'selected':''}>No / falta evidencia</option></select></label>`).join('')}</div><div class="actions"><button class="btn teal" id="evalOp">Evaluar control base</button><button class="btn secondary" id="caseBtn">▣ Ver contexto de la operación</button></div>${l.op.evaluated?`<div class="analysis-panel"><h4>Lectura de la operación</h4><p>${esc(l.op.outcome)}</p><p><strong>Clave:</strong> el registro del sistema es una evidencia, pero no reemplaza autorización, segregación, sustento ni trazabilidad.</p></div>`:''}</section>`;}
function mission2(){const l=ensureLab();return `<section class="mission-section ${!l.missions.op?'locked':''}"><div class="mission-title"><div><span class="eyebrow dark">MISIÓN 2</span><h3>Ponte en el rol del auditor</h3><p>La conciliación cuadra. Ahora decide qué técnica y prueba permiten verificar el control.</p></div><span class="mission-tag">${l.missions.audit?'✓ Completada':!l.missions.op?'Bloqueada':'Auditoría aplicada'}</span></div>${!l.missions.op?'<div class="callout orange"><strong>Primero completa la Misión 1.</strong></div>':`<div class="audit-case"><strong>Hallazgo</strong><p>La conciliación bancaria presenta saldo correcto, pero el expediente no contiene evidencia de revisión independiente.</p></div><div id="auditQuestion"></div>`}</section>`;}
function mission3(){const l=ensureLab();if(!l.missions.audit)return `<section class="mission-section locked"><div class="mission-title"><div><span class="eyebrow dark">MISIÓN 3</span><h3>¿Qué cambia si aparece nueva evidencia?</h3><p>Se desbloquea después del trabajo de auditoría.</p></div><span class="mission-tag">Bloqueada</span></div></section>`;const keys=Object.keys(CONTROL_SCENARIOS);const current=l.control.scenario?CONTROL_SCENARIOS[l.control.scenario]:null;return `<section class="mission-section"><div class="mission-title"><div><span class="eyebrow dark">MISIÓN 3</span><h3>¿Qué cambia si...?</h3><p>Elige un escenario. Uno analizado basta para completar la misión; puedes probar los demás si quieres profundizar.</p></div><span class="mission-tag">${l.missions.control?'✓ Completada':'1 escenario obligatorio'}</span></div><div class="scenario-buttons">${keys.map(k=>`<button class="scenario-btn ${l.control.scenario===k?'active':''}" data-control-scenario="${k}">${esc(CONTROL_SCENARIOS[k].title)}</button>`).join('')}</div>${current?`<div class="scenario-question"><strong>${esc(current.title)}</strong><p>${esc(current.summary)}</p></div><div class="audio-pista"><strong>🎧 Cápsula 4 · control correcto vs. control efectivo</strong><p>Extracto breve antes de decidir.</p><audio controls preload="metadata"><source src="${current.audio}" type="audio/mp4"></audio></div><div id="controlScenarioQuestion"></div>`:'<div class="callout blue"><strong>Selecciona un escenario</strong><p>La información adicional puede cambiar la conclusión aunque el saldo o registro sigan siendo correctos.</p></div>'}</section>`;}
const LAFT_EVIDENCE=[
  {label:'Perfil y actividad económica actualizados',why:'Permite establecer qué operaciones son razonables para el cliente según su actividad, tamaño y comportamiento esperado.',missing:'Sin un perfil actualizado es difícil distinguir una operación inusual de una operación propia del giro.'},
  {label:'Sustento económico / origen y propósito de la operación',why:'Ayuda a comprobar si el origen y el propósito declarado tienen una explicación económica coherente y documentable.',missing:'Sin sustento económico queda una brecha relevante sobre el origen, propósito o justificación de los fondos.'},
  {label:'Contrapartes y relación con beneficiarios',why:'Permite entender con quién opera el cliente y si las nuevas contrapartes guardan relación razonable con su actividad.',missing:'Omitir las contrapartes puede ocultar relaciones o destinos que cambian la lectura de la operación.'},
  {label:'Historial transaccional y coherencia con comportamiento habitual',why:'Permite comparar la operación actual con el patrón histórico y detectar desviaciones que merezcan explicación.',missing:'Sin historial no sabemos si estamos ante una novedad razonable o una desviación significativa del comportamiento habitual.'}
];
function laftEvidenceReviewHTML(l){const selected=LAFT_EVIDENCE.map((x,i)=>({...x,i,selected:!!l.laft.checks[i]}));const yes=selected.filter(x=>x.selected),no=selected.filter(x=>!x.selected);const intro=yes.length===4?'Revisión integral: las cuatro fuentes aportan miradas complementarias. Ninguna, por sí sola, sustituye a las demás.':`Revisión parcial: seleccionaste ${yes.length} de ${selected.length} fuentes. Lo revisado aporta información útil, pero todavía existen ángulos que podrían cambiar la conclusión.`;return `<div class="analysis-panel"><h4>Lectura de la evidencia seleccionada</h4><p>${intro}</p>${yes.length?`<div class="feedback-grid">${yes.map(x=>`<div><strong>✓ ${esc(x.label)}</strong><p>${esc(x.why)}</p></div>`).join('')}</div>`:''}${no.length?`<div class="callout orange" style="margin-top:.8rem"><strong>¿Qué falta considerar?</strong><p>No basta con una sola fuente cuando las demás pueden modificar la interpretación.</p><ul>${no.map(x=>`<li><strong>${esc(x.label)}:</strong> ${esc(x.missing)}</li>`).join('')}</ul></div>`:'<div class="callout blue" style="margin-top:.8rem"><strong>Lectura conjunta</strong><p>Perfil, sustento, contrapartes e historial se complementan: juntos permiten evaluar coherencia, trazabilidad y necesidad de escalamiento sin presumir culpabilidad.</p></div>'}</div>`;}
function mission4(){const l=ensureLab();if(!l.missions.control)return `<section class="mission-section locked"><div class="mission-title"><div><span class="eyebrow dark">MISIÓN 4</span><h3>Monitorea una alerta LA/FT</h3><p>Se desbloquea después de analizar un escenario de control.</p></div><span class="mission-tag">Bloqueada</span></div></section>`;return `<section class="mission-section"><div class="mission-title"><div><span class="eyebrow dark">MISIÓN 4</span><h3>Del control operativo a la prevención LA/FT</h3><p>Una señal inusual requiere análisis y trazabilidad. No equivale por sí sola a culpabilidad.</p></div><span class="mission-tag">${l.missions.laft?'✓ Completada':'Perfil + evidencia + decisión'}</span></div><div class="actions"><button class="btn orange" data-open-resource="video-laft">▶ Ver video corto · Prevención LA/FT</button></div><div class="laft-case"><div><span>Cliente</span><strong>Inversiones Rivera S.A.C.</strong></div><div><span>Actividad declarada</span><strong>Comercio mayorista</strong></div><div><span>Comportamiento habitual</span><strong>Transferencias locales de clientes conocidos</strong></div><div class="wide"><span>Nueva señal</span><strong>Secuencia inusual de depósitos y transferencias a nuevas contrapartes; justificación económica inicial incompleta.</strong></div></div><div class="audio-pista"><strong>🎧 Cápsula 5 · conocer, monitorear y detectar</strong><p>Escucha el extracto antes de revisar el expediente.</p><audio controls preload="metadata"><source src="assets/pista_05.m4a" type="audio/mp4"></audio></div><h4 class="subhead">Evidencia mínima a revisar antes de decidir</h4><p class="legend-mini">Selecciona las fuentes que revisarías. Después analiza qué aporta cada una y qué riesgos deja abiertos lo que no revisaste.</p><div class="check-evidence">${LAFT_EVIDENCE.map((x,i)=>`<label><input type="checkbox" data-laft-check="${i}" ${l.laft.checks[i]?'checked':''}> <span>${esc(x.label)}</span></label>`).join('')}</div><div class="actions"><button class="btn teal" id="reviewLaft">Analizar evidencia disponible</button></div>${l.laft.reviewed?`${laftEvidenceReviewHTML(l)}<div id="laftQuestion"></div>`:''}</section>`;}
function missingMissionText(){const l=ensureLab(),m=[];if(!l.missions.op)m.push('revisar operación y evidencia');if(!l.missions.audit)m.push('resolver trabajo de auditoría');if(!l.missions.control)m.push('analizar un escenario');if(!l.missions.laft)m.push('completar prevención LA/FT');return m.join(', ');}
function reportText(){const l=ensureLab();const sc=l.control.scenario?CONTROL_SCENARIOS[l.control.scenario].title:'sin escenario';const missingLaft=l.laft.checks.filter(x=>!x).length;return `Informe ejecutivo del laboratorio. Agencia Horizonte. Misión 1: ${l.op.outcome}. Misión 2: se verificó que una cifra correcta no sustituye la prueba de cumplimiento y la evidencia de revisión. Misión 3: se analizó ${sc}, reforzando que nueva evidencia puede cambiar la conclusión del control. Misión 4: se revisó una alerta LA/FT con ${missingLaft} fuente(s) de información pendiente(s). La decisión preventiva debe considerar perfil, soportes, trazabilidad y escalamiento especializado cuando corresponda. Conclusión: operación, control, auditoría y prevención deben trabajar como una cadena integrada.`;}
function renderReport(){const l=ensureLab(),missingLaft=l.laft.checks.filter(x=>!x).length;return `<div class="lab-report" id="labReport"><span class="eyebrow dark">INFORME EJECUTIVO</span><h3>Agencia Horizonte · Integridad de la operación</h3><div class="report-grid"><div><strong>Control base</strong><p>${esc(l.op.outcome)}</p></div><div><strong>Auditoría</strong><p>La exactitud de una cifra no reemplaza la evidencia de ejecución, segregación y revisión del control.</p></div><div><strong>Cambio de contexto</strong><p>${esc(CONTROL_SCENARIOS[l.control.scenario]?.title||'Escenario no identificado')}: la información adicional modificó la lectura sin inventar hechos no observados.</p></div><div><strong>Prevención LA/FT</strong><p>${missingLaft?`Quedan ${missingLaft} fuente(s) por validar; el análisis es preliminar y debe completarse antes de cerrar la revisión.`:'Las fuentes seleccionadas aparecen revisadas; mantener trazabilidad y escalamiento según la política aplicable.'}</p></div></div><div class="callout teal"><strong>Conclusión</strong><p>Una operación segura necesita evidencia del proceso, no solo un resultado correcto. El control previene, la auditoría verifica y la prevención LA/FT contextualiza y escala las alertas cuando corresponde.</p></div><div class="actions"><button class="btn secondary" id="readReportBtn">▶ Leer</button><button class="btn secondary" id="explainReportBtn">💡 Explicar</button><button class="btn secondary" data-report-speech="pause">Ⅱ Pausar</button><button class="btn secondary" data-report-speech="resume">↻ Continuar</button><button class="btn secondary" data-report-speech="stop">■ Detener</button><button class="btn orange" id="downloadReportBtn">⬇ Descargar informe</button></div></div>`;}
function renderFinalize(){const l=ensureLab(),all=Object.values(l.missions).every(Boolean);return `<div class="finalize-box"><button class="btn primary" id="finalizeLabBtn">Finalizar laboratorio → Ver informe</button><p>${all?'✓ Todas las misiones están completas. El informe está desbloqueado.':`Pendiente: ${missingMissionText()}.`}</p></div>${l.reportOpen&&all?renderReport():''}`;}
function caseHTML(){return `<div class="callout blue"><strong>Contexto de la operación</strong><p>Comercial Andina S.A.C. es cliente empresarial de Agencia Horizonte desde hace tres años. Esta mañana solicita una transferencia de S/ 48,500 a un beneficiario con el que no registra operaciones previas en el caso simulado. La instrucción aparece ingresada en el sistema, pero todavía no se ha emitido una conclusión sobre la suficiencia del control.</p></div><table class="case-table"><thead><tr><th>Elemento</th><th>Contexto disponible</th></tr></thead><tbody><tr><td>Cliente</td><td>Comercial Andina S.A.C. · relación de 3 años con la agencia.</td></tr><tr><td>Operación solicitada</td><td>Transferencia empresarial por S/ 48,500.</td></tr><tr><td>Beneficiario</td><td>Nuevo dentro del historial presentado para este ejercicio.</td></tr><tr><td>Situación</td><td>La operación está registrada en el sistema, pero el expediente aún debe ser analizado antes de concluir que el proceso está suficientemente controlado.</td></tr><tr><td>Tu tarea en el laboratorio</td><td>Revisa el caso, decide qué evidencia necesitas, evalúa los controles aplicables y determina qué aspectos permiten continuar o cuáles deben quedar observados.</td></tr></tbody></table><div class="callout orange" style="margin-top:1rem"><strong>Importante</strong><p>Este contexto no indica si los controles están correctos o incorrectos. Esa conclusión debe surgir de tu revisión durante la misión.</p></div>`;}
function renderLab(){const l=ensureLab();updateMissions();const host=$('#labHost');host.innerHTML=`${missionStrip()}<div class="lab-toolbar"><button class="btn secondary" id="caseBtnTop">▣ Contexto del caso</button><button class="btn secondary" id="resetLab">↺ Reiniciar laboratorio</button><span class="legend-mini">Una misión obligatoria por bloque · escenarios adicionales opcionales</span></div>${mission1()}${mission2()}${mission3()}${mission4()}${renderFinalize()}`;
  $$('[data-op]',host).forEach(s=>s.onchange=()=>{l.op[s.dataset.op]=s.value;});
  const openCase=()=>{$('#caseBody').innerHTML=caseHTML();openDialog('caseModal');};$('#caseBtnTop')?.addEventListener('click',openCase);$('#caseBtn')?.addEventListener('click',openCase);
  $('#evalOp')?.addEventListener('click',()=>{const out=operationOutcome(l);if(!out){toast('Verifica los cuatro campos antes de evaluar.');return;}l.op.evaluated=true;l.op.outcome=out;beep('ok');renderLab();});
  $('#resetLab')?.addEventListener('click',()=>{if(confirm('¿Reiniciar únicamente el laboratorio?')){state.lab=freshLab();renderLab();}});
  if(l.missions.op){const aq=$('#auditQuestion');if(aq)renderQuestion(aq,AUDIT_Q,l.audit.q,{onFinish:()=>{updateMissions();renderLab();setTimeout(()=>$('#auditQuestion')?.scrollIntoView({behavior:'smooth',block:'nearest'}),30);}});}
  $$('[data-control-scenario]',host).forEach(b=>b.onclick=()=>{const k=b.dataset.controlScenario;l.control.scenario=k;if(!l.control.states[k])l.control.states[k]=createQState(CONTROL_SCENARIOS[k].q);renderLab();setTimeout(()=>$('#controlScenarioQuestion')?.scrollIntoView({behavior:'smooth',block:'center'}),40);});
  if(l.control.scenario){const k=l.control.scenario,q=CONTROL_SCENARIOS[k].q,qs=l.control.states[k];const ch=$('#controlScenarioQuestion');if(ch)renderQuestion(ch,q,qs,{onFinish:()=>{l.control.completed=true;updateMissions();renderLab();}});}
  $$('[data-open-resource]',host).forEach(b=>b.onclick=()=>openResource(b.dataset.openResource,0));
  $$('[data-laft-check]',host).forEach(c=>c.onchange=()=>{l.laft.checks[Number(c.dataset.laftCheck)]=c.checked;});
  $('#reviewLaft')?.addEventListener('click',()=>{if(!l.laft.checks.some(Boolean)){toast('Selecciona al menos una fuente de evidencia para analizar qué aporta y qué queda pendiente.');return;}l.laft.reviewed=true;beep('soft');renderLab();setTimeout(()=>$('#laftQuestion')?.scrollIntoView({behavior:'smooth',block:'center'}),30);});
  if(l.laft.reviewed){const lh=$('#laftQuestion');if(lh)renderQuestion(lh,LAFT_Q,l.laft.q,{onFinish:()=>{updateMissions();renderLab();}});}
  $('#finalizeLabBtn')?.addEventListener('click',()=>{updateMissions();if(!Object.values(l.missions).every(Boolean)){toast('Aún falta: '+missingMissionText());return;}l.reportOpen=true;beep('ok');renderLab();setTimeout(()=>$('#labReport')?.scrollIntoView({behavior:'smooth',block:'start'}),40);});
  $('#readReportBtn')?.addEventListener('click',()=>speak(reportText()));$('#explainReportBtn')?.addEventListener('click',()=>speak('El informe integra cuatro capas. Primero verifica la operación y su evidencia. Luego comprueba si el control funciona con técnicas de auditoría. Después observa cómo nueva información puede cambiar la conclusión. Finalmente analiza una alerta de prevención sin confundir señal con culpabilidad.'));
  $$('[data-report-speech]',host).forEach(b=>b.onclick=()=>{if(b.dataset.reportSpeech==='pause')pauseSpeech();if(b.dataset.reportSpeech==='resume')resumeSpeech();if(b.dataset.reportSpeech==='stop')stopSpeech();});
  $('#downloadReportBtn')?.addEventListener('click',downloadReport);updateMissions();
}
function downloadReport(){const text=reportText()+`\n\nElaborado por: Mg. Ricardo Puccio Alvarado · ripual@gmail.com`;const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Informe_Laboratorio_Sesion_5_IPN.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}

/* quiz */
function resetQuiz(){quizCorrectPositions=balancedPositions(DATA.quiz);state.quizOrder=shuffleIndices(DATA.quiz.length);state.quizIndex=0;state.quizStates={};state.quizScore=0;$('#scoreCard').classList.add('hidden');renderQuizItem();}
function ensureQuiz(){if(!state.quizOrder.length)resetQuiz();else renderQuizItem();}
function quizState(idx,q){if(!state.quizStates[idx]){const visualIndex=state.quizOrder.indexOf(idx);state.quizStates[idx]=createQState(q,orderWithTarget(q,quizCorrectPositions[visualIndex]??randomInt(q.options.length)));}return state.quizStates[idx];}
function renderQuizItem(){if(state.quizIndex>=DATA.quiz.length){finishQuiz();return;}const qi=state.quizOrder[state.quizIndex],q=DATA.quiz[qi],qs=quizState(qi,q);$('#quizBadge').textContent=`Pregunta ${state.quizIndex+1} / ${DATA.quiz.length}`;$('#quizBar').style.width=`${state.quizIndex/DATA.quiz.length*100}%`;$('#quizHost').innerHTML='<div id="quizQuestion"></div><div id="quizNext"></div>';renderQuestion($('#quizQuestion'),q,qs,{onFinish:r=>{if(r.correct&&!qs._counted){state.quizScore++;qs._counted=true;}renderQuizItem();}});if(questionDone(qs)){$('#quizNext').innerHTML=`<button class="btn teal" style="margin-top:.7rem">${state.quizIndex===DATA.quiz.length-1?'Ver resultado':'Siguiente pregunta →'}</button>`;$('#quizNext button').onclick=()=>{state.quizIndex++;renderQuizItem();window.scrollTo({top:0,behavior:'smooth'});};}}
function finishQuiz(){$('#quizBar').style.width='100%';$('#quizHost').innerHTML='';$('#scoreCard').classList.remove('hidden');$('#scoreTitle').textContent=`${state.quizScore} de ${DATA.quiz.length} respuestas correctas sin Ruta correcta`;$('#scoreText').textContent=state.quizScore>=4?'Integras control, auditoría y prevención con bastante solidez.':state.quizScore>=3?'Tienes una base funcional. Revisa especialmente evidencia, segregación y tratamiento de alertas.':'Conviene regresar a las tarjetas y al laboratorio antes de repetir la comprobación.';}

/* resources */
function renderResources(){const host=$('#resourceGrid');host.innerHTML=DATA.resources.map(r=>`<article class="resource-card"><div class="resource-thumb"><img src="${r.thumb}" alt="Miniatura de ${esc(r.title)}"></div><div class="resource-copy"><h3>${esc(r.title)}</h3><p>${esc(r.desc)}</p><button class="btn secondary" data-open-resource="${r.id}">Abrir dentro del programa</button></div></article>`).join('');$$('[data-open-resource]',host).forEach(b=>b.onclick=()=>openResource(b.dataset.openResource,0));}
const VIDEO_MAP={'video-main':'assets/video_apertura.mp4','video-agencias':'assets/video_agencias.mp4','video-laft':'assets/video_laft.mp4'};
function openResource(id,index=0){if(VIDEO_MAP[id])return openFloatingVideo(id);resourceContext={id,index};renderResource();openDialog('resourceModal');}
function openFloatingVideo(id){const r=DATA.resources.find(x=>x.id===id),v=$('#floatingVideo');v.src=VIDEO_MAP[id];v.setAttribute('aria-label',r?.title||'Video');openDialog('videoModal');setTimeout(()=>v.play().catch(()=>{}),80);}
function resourceMeta(){return DATA.resources.find(x=>x.id===resourceContext?.id);}
function resourceSpeech(type){const id=resourceContext.id,idx=resourceContext.index||0;if(id==='ppt')return RT.ppt?.[idx]?.[type]||'';if(id==='pdf')return RT.pdf?.[idx]?.[type]||'';return RT[id]?.[type]||'';}
function renderResource(){const r=resourceMeta();if(!r)return;$('#resourceType').textContent=r.type.toUpperCase();$('#resourceTitle').textContent=r.title;const body=$('#resourceBody'),foot=$('#resourceFooter');body.className='resource-body';if(r.id==='ppt'){const i=Math.max(0,Math.min(17,resourceContext.index||0));resourceContext.index=i;body.innerHTML=`<div class="fit-stage"><img src="assets/ppt/slide-${String(i+1).padStart(2,'0')}.png" alt="Diapositiva ${i+1} de 18" data-image="assets/ppt/slide-${String(i+1).padStart(2,'0')}.png"></div>`;foot.innerHTML=`<div class="resource-nav"><button data-rnav="-1" ${i===0?'disabled':''}>← Anterior</button><strong>Diapositiva ${i+1} / 18</strong><button data-rnav="1" ${i===17?'disabled':''}>Siguiente →</button></div>${speechControlsHTML()}`;bindResourceNav(18);}else if(r.id==='pdf'){const i=Math.max(0,Math.min(9,resourceContext.index||0));resourceContext.index=i;body.innerHTML=`<div class="fit-stage"><img src="assets/pdf/page-${String(i+1).padStart(2,'0')}.png" alt="Página ${i+1} de 10" data-image="assets/pdf/page-${String(i+1).padStart(2,'0')}.png"></div>`;foot.innerHTML=`<div class="resource-nav"><button data-rnav="-1" ${i===0?'disabled':''}>← Anterior</button><strong>Página ${i+1} / 10</strong><button data-rnav="1" ${i===9?'disabled':''}>Siguiente →</button></div>${speechControlsHTML()}`;bindResourceNav(10);}else if(r.id==='infographic'){body.innerHTML=`<div class="fit-stage"><img src="assets/infografia_sesion5.png" alt="Guía de Integridad Bancaria" data-image="assets/infografia_sesion5.png"></div>`;foot.innerHTML=`<div class="resource-nav"><strong>Infografía integradora</strong></div>${speechControlsHTML()}`;}else if(r.id==='audio'){body.innerHTML=`<div class="audio-stage"><div class="audio-card"><img src="assets/thumbs/audio.png" alt="Resumen de audio"><h3>Blindaje bancario contra el lavado de activos</h3><audio controls preload="metadata"><source src="assets/podcast_completo.m4a" type="audio/mp4"></audio></div></div>`;foot.innerHTML=`<div class="resource-nav"><strong>Audio completo</strong></div>${speechControlsHTML()}`;}bindSpeechControls(foot,type=>resourceSpeech(type));$('[data-image]',body)?.addEventListener('click',e=>openImage(e.currentTarget.dataset.image,e.currentTarget.alt));}
function bindResourceNav(total){$$('[data-rnav]',$('#resourceFooter')).forEach(b=>b.onclick=()=>{resourceContext.index=Math.max(0,Math.min(total-1,(resourceContext.index||0)+Number(b.dataset.rnav)));stopSpeech();renderResource();});}
function openImage(src,alt='Vista ampliada'){$('#imageModalImg').src=src;$('#imageModalImg').alt=alt;openDialog('imageModal');}

/* cierre detonante */
const CLOSING_Q={text:'Si una operación aparece correctamente registrada en el sistema, ¿eso demuestra por sí solo que fue autorizada, que los controles funcionaron y que no existe una señal de riesgo?',options:[[OPENING_OPTIONS[0],0],[OPENING_OPTIONS[1],1],[OPENING_OPTIONS[2],0]],correct:'El registro correcto es solo una parte de la evidencia. Deben verificarse autorización, segregación, funcionamiento de controles y contexto de riesgo.',application:'Esta es la idea que recorre todo el laboratorio.',contrast:'Las otras opciones convierten el registro o el monto en sustitutos del control.',rule:'Registro correcto ≠ proceso totalmente validado.',wrong1:'Recuerda los hallazgos del laboratorio: un saldo o registro puede estar bien y aun existir una debilidad de control.',route:['Verifica el registro.','Comprueba autorización y segregación.','Busca evidencia de ejecución.','Analiza contexto y alertas.'],routeSummary:'La Ruta correcta integra registro, control y contexto.'};
function renderClosingReview(){const host=$('#closingOpeningReview');if(!host)return;const initial=state.opening.selected===null?'No registraste una respuesta inicial.':OPENING_OPTIONS[state.opening.selected];let inner=`<span class="eyebrow dark">VOLVAMOS A LA PREGUNTA INICIAL</span><h3>Tu respuesta original</h3><div class="initial-answer">${esc(initial)}</div>`;if(!state.closingQ){inner+=`<p>Ahora puedes validar tu respuesta inicial o cambiarla antes de comprobarla.</p><div class="actions"><button class="btn primary" id="validateInitial" ${state.opening.selected===null?'disabled':''}>Validar mi respuesta inicial</button><button class="btn secondary" id="changeInitial">Cambiar mi respuesta</button></div><div id="closingQHost"></div>`;}else inner+=`<div id="closingQHost"></div>`;host.innerHTML=inner;$('#validateInitial')?.addEventListener('click',()=>{const q=createQState(CLOSING_Q,shuffleIndices(CLOSING_Q.options.length));q.selected=state.opening.selected;state.closingQ=q;renderClosingReview();});$('#changeInitial')?.addEventListener('click',()=>{state.closingQ=createQState(CLOSING_Q,shuffleIndices(CLOSING_Q.options.length));renderClosingReview();});if(state.closingQ)renderQuestion($('#closingQHost'),CLOSING_Q,state.closingQ,{onFinish:()=>{}});}

/* bindings */
$('#aulaHomeBtn')?.addEventListener('click',returnToAulaVirtual);
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('.modal-close').forEach(b=>b.onclick=()=>closeDialog(b.dataset.close));$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)closeDialog(d.id);}));$('#prevConcept').onclick=()=>{conceptIndex=Math.max(0,conceptIndex-1);renderConceptModal();setTimeout(()=>$('#conceptBody').scrollTo({top:0}),20);};$('#nextConcept').onclick=()=>{conceptIndex=Math.min(DATA.concepts.length-1,conceptIndex+1);renderConceptModal();setTimeout(()=>$('#conceptBody').scrollTo({top:0}),20);};$('#resourceFull').onclick=()=>toggleFullscreen($('#resourceShell'));$('#fullBtn').onclick=()=>toggleFullscreen($('.app-shell'));$('#fontMinus').onclick=()=>{state.font=Math.max(.88,state.font-.08);updateFont();};$('#fontPlus').onclick=()=>{state.font=Math.min(1.24,state.font+.08);updateFont();};$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn').textContent=state.sound?'🔊':'🔇';};$('#themeBtn').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';applyTheme();};$('#layoutSelect').onchange=e=>{state.layout=e.target.value;applyLayout();};$('#restartQuiz').onclick=resetQuiz;$('#resetAll').onclick=()=>{if(confirm('¿Reiniciar todo el programa y borrar el progreso de esta ejecución?'))location.reload();};$$('[data-open-resource]').forEach(b=>b.onclick=()=>openResource(b.dataset.openResource,Number(b.dataset.resourceIndex||0)));window.addEventListener('resize',()=>{if(state.layout==='auto')applyLayout();});if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=()=>{};
applyLayout();applyTheme();updateFont();renderOpening();renderConceptCards();renderLab();renderResources();resetQuiz();

/* aula virtual */
async function returnToAulaVirtual(){
  if(typeof stopSpeech==='function')stopSpeech();
  try{if(document.fullscreenElement)await document.exitFullscreen();}catch(_e){}
  window.location.href=new URL('../',window.location.href).href;
}
